Completed css-brochure-form challenge.
thomas-tahk/m1-0522-code-solutions pull request #16
Opened 2022-05-20 05:01 UTC by thomas-tahk

![css-brochure-form](https://user-images.githubusercontent.com/10647431/169453710-83ce0d81-41db-440e-98f3-8756534db282.png)

Not identical because I don't know exact numbers for paddings, margins, etc. But I believe this is somewhat close.

2022-05-20 17:09 UTC, Zhiwutian requested changes
Looking really good overall, a few updates are needed. 
1. Make sure the form is centered on the page, this is commonly done by wrapping the entire page in a `container` element and putting set width on it then using margin auto to center it on the page.
3.  make sure the text alignment over the inputs matches the example, the label for the final input is longer than the input
4. make sure the button alignment matches the example

2022-05-20 17:09 UTC, Zhiwutian commented on css-brochure-form/styles.css
> +  float: right;
I would avoid using float here, text align right should work well. float is only for wrapping text around images.

2022-05-23 22:59 UTC, thomas-tahk commented
Updated Screenshot with latest commit:
![css-brochure-form-edited](https://user-images.githubusercontent.com/10647431/169917852-226e4d04-9be1-4485-b4fc-58dffe5dadef.png)

2022-05-23 23:21 UTC, Zhiwutian approved these changes
👍🏼

2022-05-24 00:58 UTC, merged